// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACyS6kmVcXh4OdmMuUSTTIFOR83URBgmk',
    appId: '1:227929817804:web:da09bc71b077363985b869',
    messagingSenderId: '227929817804',
    projectId: 'potokopi',
    authDomain: 'potokopi.firebaseapp.com',
    storageBucket: 'potokopi.firebasestorage.app',
    measurementId: 'G-F3RFSWFN99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQLm0_7X7dsglrX2h8IA2d27UN68WiE8',
    appId: '1:227929817804:android:76620d2e4363457985b869',
    messagingSenderId: '227929817804',
    projectId: 'potokopi',
    storageBucket: 'potokopi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YJD-DDoUZ0CK-Sv1d14e4Q41nTQG2Sk',
    appId: '1:227929817804:ios:7cd1070abbb1f04585b869',
    messagingSenderId: '227929817804',
    projectId: 'potokopi',
    storageBucket: 'potokopi.firebasestorage.app',
    iosBundleId: 'com.example.porina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YJD-DDoUZ0CK-Sv1d14e4Q41nTQG2Sk',
    appId: '1:227929817804:ios:7cd1070abbb1f04585b869',
    messagingSenderId: '227929817804',
    projectId: 'potokopi',
    storageBucket: 'potokopi.firebasestorage.app',
    iosBundleId: 'com.example.porina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACyS6kmVcXh4OdmMuUSTTIFOR83URBgmk',
    appId: '1:227929817804:web:21a5488d5d86d0a885b869',
    messagingSenderId: '227929817804',
    projectId: 'potokopi',
    authDomain: 'potokopi.firebaseapp.com',
    storageBucket: 'potokopi.firebasestorage.app',
    measurementId: 'G-HVJT2WPQXT',
  );
}
